root_base:
  - 6.28.0
  - 6.28.10
c_stdlib:
  - sysroot  # [linux]
  - maxosx_deployment_target  # [osx]
  - vs  # [win]
c_stdlib_version:  # [unix]
  - 2.12  # [linux and x86_64]
  - 2.17  # [linux and not x86_64]
  - 10.9  # [osx and x86_64]
  - 11.0  # [osx and arm64]

