conda_forge_output_validation: true
os_version:
  linux_64: cos7
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test_on_native_only: true
